"I DID THIS CODE IN THE GOOGLE COLAB" YOU MUST ALSO TRY THIS COLAB ONLY 
# -*- coding: utf-8 -*-
"""PoemGenerator(chatbot).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNtrp2Zz6_PSMhBam72T_sKWW3lVBL_L
"""

!pip install torch transformers==4.43.3 accelerate gradio

!pip install transformers gradio --quiet

from transformers import pipeline
import gradio as gr

# Load the GPT-Neo 125M model for text generation
generator = pipeline("text-generation", model="EleutherAI/gpt-neo-125M")

# Define the function used by Gradio
def generate_poem(prompt):
    result = generator(prompt, max_length=50, do_sample=True, temperature=0.8)
    return result[0]['generated_text']

# Create the Gradio interface
demo = gr.Interface(
    fn=generate_poem,
    inputs="text",
    outputs="text",
    title="Poem Generator",
    description="Enter a prompt and let the model generate a short poem."
)

# Launch the app
demo.launch(debug=True)
